USE [ACES_Processing]
GO

/****** Object:  StoredProcedure [dbo].[usp_duplicatefitment]    Script Date: 9/29/2020 3:24:06 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


-- =============================================
-- Author:		GM
-- Create date: 8/30/2018
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[usp_duplicatefitment]
@lc char(2)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;


--truncate table [dbo].[PaStockFeedDuplicates];




Insert into [dbo].[PAStockFeedAnalysis]
Select [pastockid]
      ,[ControlID]
      ,[sfran]
      ,[spart]
      ,[sku]
      ,[Aspiration]
      ,[BaseVehicle]
      ,[BedLength]
      ,[BedType]
      ,[BodyNumDoors]
      ,[BodyType]
      ,[BrakeABS]
      ,[BrakeSystem]
      ,[CylinderHeadType]
      ,[DriveType]
      ,[DisplayOrder]
      ,[EngineBase]
      ,[OrigEngineBase]
      ,[EngineDesignation]
      ,[EngineMfr]
      ,[EngineVIN]
      ,[EngineVersion]
      ,[EngineBlock]
      ,[EngineBoreStroke]
      ,[EquipmentBase]
      ,[EquipmentModel]
      ,[FrontBrakeType]
      ,[FrontSpringType]
      ,[FuelDeliverySubType]
      ,[FuelSystemControlType]
      ,[FuelSystemDesign]
      ,[FuelDeliveryType]
      ,[FuelType]
      ,[IgnitionSystemType]
      ,[make]
      ,[mfr]
      ,[MfrBodyCode]
      ,[MfrLabel]
      ,[model]
      ,[Note1]
      ,[Note2]
      ,[Note3]
      ,[Note4]
      ,[Note5]
      ,[Note6]
      ,[Note7]
      ,[Note8]
      ,[Note9]
      ,[Note10]
      ,[Note11]
      ,[Note12]
      ,[Note13]
      ,[Note14]
      ,[Note15]
      ,[Note16]
      ,[PartTerminologyid]
      ,[origPartTermID]
      ,[PositionID]
      ,[poweroutput]
      ,[origPositionID]
      ,[FitNote]
      ,[RearBrakeType]
      ,[RearSpringType]
      ,[Region]
      ,[SteeringSystem]
      ,[SteeringType]
      ,[Submodel]
      ,[TransferDate]
      ,[TransmissionControlType]
      ,[TransmissionMfr]
      ,[TransmissionNumSpeeds]
      ,[TransmissionType]
      ,[TransElecControlled]
      ,[TransmissionBase]
      ,[TransmissionMfrCode]
      ,[ValvesPerEngine]
      ,[VehicleType]
      ,[WheelBase]
      ,[PerCarQty]
      ,[Years]
      ,[cylinders]
      ,[blocktype]
      ,[liter]
      ,[Invalid]
      ,[udfspart]
      ,[LoadDT]
      ,[UpdateDT] from aces.[mst].[PAStockFeed_final] where sfran = @lc and invalid is null

insert into [dbo].[PaStockFeedDuplicates] ([sku]
           ,[Aspiration]
           ,[BaseVehicle]
           ,[BedLength]
           ,[BedType]
           ,[BodyNumDoors]
           ,[BodyType]
           ,[BrakeABS]
           ,[BrakeSystem]
           ,[CylinderHeadType]
           ,[DriveType]
           ,[DisplayOrder]
           ,[EngineDesignation]
           ,[EngineMfr]
           ,[EngineVIN]
           ,[EngineVersion]
           ,[EngineBoreStroke]
           ,[EquipmentBase]
           ,[EquipmentModel]
           ,[FrontBrakeType]
           ,[FrontSpringType]
           ,[FuelDeliverySubType]
           ,[FuelSystemControlType]
           ,[FuelSystemDesign]
           ,[FuelDeliveryType]
           ,[FuelType]
           ,[IgnitionSystemType]
           ,[make]
           ,[mfr]
           ,[MfrBodyCode]
          ,[MfrLabel]
           ,[model]
         ,[Note1]
        ,[Note2]
           ,[PartTerminologyid]
           ,[PositionID]
           ,[poweroutput]
           ,[RearBrakeType]
           ,[RearSpringType]
           ,[Region]
           ,[SteeringSystem]
           ,[SteeringType]
           ,[Submodel]
           ,[TransferDate]
           ,[TransmissionControlType]
           ,[TransmissionMfr]
           ,[TransmissionNumSpeeds]
           ,[TransmissionType]
           ,[TransElecControlled]
           ,[TransmissionBase]
           ,[TransmissionMfrCode]
           ,[ValvesPerEngine]
           ,[VehicleType]
           ,[WheelBase]
           ,[PerCarQty]
           ,[Years]
           ,[cylinders]
           ,[blocktype]
           ,[liter]
           ,[counter])
SELECT [sku]
      ,[Aspiration]
      ,[BaseVehicle]
      ,[BedLength]
      ,[BedType]
      ,[BodyNumDoors]
      ,[BodyType]
      ,[BrakeABS]
      ,[BrakeSystem]
      ,[CylinderHeadType]
      ,[DriveType]
      ,[DisplayOrder]
      ,[EngineDesignation]
      ,[EngineMfr]
      ,[EngineVIN]
      ,[EngineVersion]
      ,[EngineBoreStroke]
      ,[EquipmentBase]
      ,[EquipmentModel]
      ,[FrontBrakeType]
      ,[FrontSpringType]
      ,[FuelDeliverySubType]
      ,[FuelSystemControlType]
      ,[FuelSystemDesign]
      ,[FuelDeliveryType]
      ,[FuelType]
      ,[IgnitionSystemType]
      ,[make]
      ,[mfr]
      ,[MfrBodyCode]
    ,[MfrLabel]
      ,[model]
     ,[Note1]
     ,[Note2]
      ,[PartTerminologyid]
      ,[PositionID]
      ,[poweroutput]
      ,[RearBrakeType]
      ,[RearSpringType]
      ,[Region]
      ,[SteeringSystem]
      ,[SteeringType]
      ,[Submodel]
      ,[TransferDate]
      ,[TransmissionControlType]
      ,[TransmissionMfr]
      ,[TransmissionNumSpeeds]
      ,[TransmissionType]
      ,[TransElecControlled]
      ,[TransmissionBase]
      ,[TransmissionMfrCode]
      ,[ValvesPerEngine]
      ,[VehicleType]
      ,[WheelBase]
      ,[PerCarQty]
      ,[Years]
      ,[cylinders]
      ,[blocktype]
      ,[liter]   
	  ,count(*) counter
    FROM [dbo].[PAStockFeedAnalysis]
	group by [sku]
      ,[Aspiration]
      ,[BaseVehicle]
      ,[BedLength]
      ,[BedType]
      ,[BodyNumDoors]
      ,[BodyType]
      ,[BrakeABS]
      ,[BrakeSystem]
      ,[CylinderHeadType]
      ,[DriveType]
      ,[DisplayOrder]
      ,[EngineDesignation]
      ,[EngineMfr]
      ,[EngineVIN]
      ,[EngineVersion]
      ,[EngineBoreStroke]
      ,[EquipmentBase]
      ,[EquipmentModel]
      ,[FrontBrakeType]
      ,[FrontSpringType]
      ,[FuelDeliverySubType]
      ,[FuelSystemControlType]
      ,[FuelSystemDesign]
      ,[FuelDeliveryType]
      ,[FuelType]
      ,[IgnitionSystemType]
      ,[make]
      ,[mfr]
      ,[MfrBodyCode]
    ,[MfrLabel]
      ,[model]
    ,[Note1]
    ,[Note2]
      ,[PartTerminologyid]
      ,[PositionID]
      ,[poweroutput]
      ,[RearBrakeType]
      ,[RearSpringType]
      ,[Region]
      ,[SteeringSystem]
      ,[SteeringType]
      ,[Submodel]
      ,[TransferDate]
      ,[TransmissionControlType]
      ,[TransmissionMfr]
      ,[TransmissionNumSpeeds]
      ,[TransmissionType]
      ,[TransElecControlled]
      ,[TransmissionBase]
      ,[TransmissionMfrCode]
      ,[ValvesPerEngine]
      ,[VehicleType]
      ,[WheelBase]
      ,[PerCarQty]
      ,[Years]
      ,[cylinders]
      ,[blocktype]
      ,[liter]    
	  having count(*) > 1;


	  truncate table [dbo].[PAStockFeedAnalysis];




END
GO


